export const dataSource = [
  {
    key: '1',
    ordersId: 'XKLK21738',
    nameProduct: 'Kính iPhone 14 Pro Max',
    price: '70,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'YC',
    type: 'Linh kiện cần',
    userName: 'Bình',
  },
  {
    key: '2',
    ordersId: 'XKLK21738',
    nameProduct: 'Ron viền iPhone 14 Pro Max',
    price: '90,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'DXK',
    type: 'Linh kiện cần',
    userName: 'Bình',
  },
  {
    key: '3',
    ordersId: 'XKLK21738',
    nameProduct: 'Ron viền iPhone 14 Pro Max',
    price: '90,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'H',
    type: 'Linh kiện cần',
    userName: 'Bình',
  },
  {
    key: '4',
    ordersId: 'XKLK21738',
    nameProduct: 'Ron viền iPhone 14 Pro Max',
    price: '90,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'DXN',
    type: 'Linh kiện cần',
    userName: 'Bình',
  },
  {
    key: '5',
    ordersId: 'XKLK21738',
    nameProduct: 'Ron viền iPhone 14 Pro Max',
    price: '90,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'Cần xác nhận',
    type: 'Linh kiện cần',
    userName: 'Bình',
  },
  {
    key: '6',
    ordersId: 'XKLK21738',
    nameProduct: 'Kính iPhone 14 Pro Max',
    price: '70,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'YC',
    type: 'Linh kiện cần',
    userName: 'Bình',
  },
  {
    key: '7',
    ordersId: 'XKLK21738',
    nameProduct: 'Ron viền iPhone 14 Pro Max',
    price: '90,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'DXK',
    type: 'Linh kiện cần',
    userName: 'Bình',
  },
  {
    key: '8',
    ordersId: 'XKLK21738',
    nameProduct: 'Ron viền iPhone 14 Pro Max',
    price: '90,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'H',
    type: 'Linh kiện cần',
    userName: 'Bình',
  },
  {
    key: '9',
    ordersId: 'XKLK21738',
    nameProduct: 'Ron viền iPhone 14 Pro Max',
    price: '90,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'DXN',
    type: 'Linh kiện cần',
    userName: 'Bình',
  },
  {
    key: '10',
    ordersId: 'XKLK21738',
    nameProduct: 'Ron viền iPhone 14 Pro Max',
    price: '90,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'Cần xác nhận',
    type: 'Linh kiện cần',
    userName: 'Bình',
  },
  {
    key: '11',
    ordersId: 'XKLK21738',
    nameProduct: 'Kính iPhone 14 Pro Max',
    price: '2,200,000đ',
    warehouse: 'LK 247',
    orderProductId: 'PBH98142',
    status: 'YC',
    type: 'Linh kiện cần',
    userName: 'Bình',
  },
  {
    key: '12',
    ordersId: 'XKLK21738',
    nameProduct: 'Ron viền iPhone 14 Pro Max',
    price: '90,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'DXK',
    type: 'Linh kiện cần',
    userName: 'Tuấn',
  },
  {
    key: '13',
    ordersId: 'XKLK21738',
    nameProduct: 'Ron viền iPhone 14 Pro Max',
    price: '90,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'H',
    type: 'Linh kiện cần',
    userName: 'Tuấn',
  },
  {
    key: '14',
    ordersId: 'XKLK21738',
    nameProduct: 'Ron viền iPhone 14 Pro Max',
    price: '1,700,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'DXN',
    type: 'Linh kiện cần',
    userName: 'Bình',
  },
  {
    key: '15',
    ordersId: 'XKLK21738',
    nameProduct: 'Ron viền iPhone 14 Pro Max',
    price: '90,000đ',
    warehouse: 'TLM',
    orderProductId: 'PBH98142',
    status: 'Cần xác nhận',
    type: 'Linh kiện cần',
    userName: 'Tuấn',
  },
];
